export { default as git } from './git.png';
export { default as javascript } from './javascript.png';
export { default as nextjs } from './nextjs.png';
export { default as reactjs } from './reactjs.png';
export { default as redux } from './redux.png';
export { default as solidity } from './solidity.png';
export { default as tailwind } from './tailwind.png';
export { default as threejs } from './threejs.svg';
export { default as typescript } from './typescript.png';
